### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by volzkzg**
In case you can not find the option --check

### CODE REVIEW

**Comment by davidalber** [comment]
Hi @volzkzg. Thanks for your contribution!

The purpose of this repository is to verify the example Travis CI config in [rustfmt's README](https://github.com/rust-lang-nursery/rustfmt) works. Thus, the .travis.yml file here is expected to match the snippet in the rustfmt snippet. I would be happy to merge your changes if they are first merged to rustfmt.

The build for this change still failed on the `--check` flag.
```
$ rustup component add rustfmt-preview
$ rustup self update
$ cargo fmt --all -- --check
Unrecognized option: 'check'

The command "cargo fmt --all -- --check" exited with 1.
```

**Comment by volzkzg** [comment]
@davidalber Hi David, I solved the problem `Unrecognized option: check` by add the line 
```
rustup self update
```
in my case. That's why I made this contribution when I saw you have the same problem. 

Let me check what's the real problem here.

**Comment by davidalber** [comment]
I believe it's because you are using nightly.

**Comment by volzkzg** [comment]
Yeah, that's true. So I guess it will be solved when next stable version releases.

**Comment by davidalber** [comment]
:+1: In rust-lang-nursery/rustfmt#2688, I asked when that will happen.

**Pull request closed without merging**
